### ISSUE TITLE
src.enums missing

### ISSUE THREAD

**Issue by Draudnaut** [dvirsamuel/NewtonRaphsonInversion#1]
Hi!
When I running the code, I found that 
/home/zzz/miniconda3/envs/newton-raphson/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/zzz/Engineering/NewtonRaphsonInversion/main.py", line 6, in <module>
    from src.euler_scheduler import MyEulerAncestralDiscreteScheduler
  File "/home/zzz/Engineering/NewtonRaphsonInversion/src/euler_scheduler.py", line 9, in <module>
    from src.eunms import Epsilon_Update_Type
ModuleNotFoundError: No module named 'src.eunms'
is there a file named  enums in the src missing?

**Comment by RobertLau666** [comment]
Create a new eunms.py in the src folder, the value of OVERRIDE is arbitrarily specified:
```
from enum import Enum

class Epsilon_Update_Type(Enum):
    OVERRIDE = 1
```
